import Link from 'next/link';
import {api} from '@/lib/api/client';
import {PartCard} from '@/components/PartCard';
import {InventoryFilters} from '@/components/InventoryFilters';
import type {Category,Paginated,Part} from '@/types/api';
export const dynamic='force-dynamic';
export default async function InventoryPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const sp=await searchParams;const q=(k:string):string|undefined=>Array.isArray(sp[k])?sp[k][0]:sp[k];const params=new URLSearchParams();for(const k of ['year','make','model','categoryId','keyword','page','limit'])if(q(k))params.set(k,q(k)!);if(!params.get('limit'))params.set('limit','24');if(!params.get('page'))params.set('page','1');let result:Paginated<Part>={data:[],meta:{page:1,limit:24,total:0,totalPages:0}};let error='';try{result=await api.inventory.search(params)}catch(e){error=e instanceof Error?e.message:'Unable to load inventory.'}let categories:Category[]=[];let years:number[]=[];try{[categories,years]=await Promise.all([api.categories(),api.vehicles.years()])}catch{}return <main className="mx-auto max-w-7xl overflow-x-hidden px-4 py-8 md:py-12"><div className="mb-8 motion-fade-up"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-700">Yard inventory</p><h1 className="mt-1 text-4xl font-black">Find a Part</h1><p className="mt-2 max-w-2xl text-gray-600">Search current inventory by vehicle, category, keyword and page.</p></div><div className="grid min-w-0 gap-6 lg:grid-cols-[280px_1fr]"><InventoryFilters categories={categories} years={years} initial={{keyword:q('keyword'),year:q('year'),make:q('make'),model:q('model'),categoryId:q('categoryId')}}/><section className="min-w-0">{error?<div className="border border-red-200 bg-red-50 p-5 text-red-800">{error}</div>:result.data.length?<><div className="mb-4 flex flex-wrap items-center justify-between gap-2 text-sm"><span className="font-bold">{result.meta.total} result{result.meta.total===1?'':'s'}</span><span>Page {result.meta.page} of {Math.max(result.meta.totalPages,1)}</span></div><div className="motion-stagger grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{result.data.map(p=><PartCard key={p.id} part={p}/>)}</div><Pagination page={result.meta.page} totalPages={result.meta.totalPages} params={params}/></>:<EmptyInventory/>}</section></div></main>}
function EmptyInventory(){return <div className="border border-gray-200 bg-white p-7 sm:p-10 motion-fade-up"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-700">Inventory search</p><h2 className="mt-2 text-xl font-black">No parts currently match your search.</h2><p className="mt-2 text-sm leading-6 text-gray-600">Our yard inventory changes frequently. Call the yard for assistance finding a specific part.</p><div className="mt-5 flex flex-col gap-2 sm:flex-row sm:justify-center"><a href="tel:+16785803666" className="inline-flex min-h-11 items-center justify-center bg-[#d97706] px-5 text-sm font-black text-white">Call Yard</a><Link href="/inventory" className="inline-flex min-h-11 items-center justify-center border border-gray-300 px-5 text-sm font-black">Clear Search</Link></div></div></div>}
function Pagination({page,totalPages,params}:{page:number;totalPages:number;params:URLSearchParams}){if(totalPages<=1)return null;const make=(n:number)=>{const p=new URLSearchParams(params);p.set('page',String(n));return `/inventory?${p}`};const start=Math.max(1,Math.min(page-2,totalPages-4));const end=Math.min(totalPages,Math.max(5,page+2));const pages=Array.from({length:end-start+1},(_,i)=>start+i);return <nav aria-label="Inventory pages" className="mt-9 flex flex-wrap items-center justify-center gap-2">{page>1&&<a className="min-h-11 border border-gray-300 bg-white px-3 py-2 text-sm font-bold transition hover:border-gray-400 hover:bg-gray-50" href={make(page-1)}>Previous</a>}{start>1&&<><a className="grid h-11 w-11 place-items-center border border-gray-300 bg-white text-sm font-bold hover:border-gray-400" href={make(1)}>1</a>{start>2&&<span aria-hidden="true" className="px-1 text-gray-400">...</span>}</>}{pages.map(n=><a key={n} aria-current={n===page?'page':undefined} className={`grid h-11 w-11 place-items-center border text-sm font-black transition ${n===page?'border-[#111827] bg-[#111827] text-white':'border-gray-300 bg-white hover:border-gray-400 hover:bg-gray-50'}`} href={make(n)}>{n}</a>)}{end<totalPages&&<>{end<totalPages-1&&<span aria-hidden="true" className="px-1 text-gray-400">...</span>}<a className="grid h-11 w-11 place-items-center border border-gray-300 bg-white text-sm font-bold hover:border-gray-400" href={make(totalPages)}>{totalPages}</a></>}{page<totalPages&&<a className="min-h-11 border border-gray-300 bg-white px-3 py-2 text-sm font-bold transition hover:border-gray-400 hover:bg-gray-50" href={make(page+1)}>Next</a>}</nav>}
