import Link from 'next/link';
import {ArrowRight,Phone,MapPin,Wrench,ShieldCheck,Truck} from 'lucide-react';
import {VehicleLookup} from '@/components/VehicleLookup';
import {VinDecoder} from '@/components/VinDecoder';
import {api} from '@/lib/api/client';
import {PartCard} from '@/components/PartCard';
import type {Part} from '@/types/api';
export const revalidate=60;
export default async function Home(){
  let parts:Part[]=[]; let inventoryError=false;
  try{const p=new URLSearchParams({page:'1',limit:'8'});parts=(await api.inventory.search(p)).data}catch{inventoryError=true}
  return <main className="overflow-x-hidden">
    <section className="bg-[#111827] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 md:grid-cols-[1.2fr_.8fr] md:items-end md:py-20"><div className="motion-fade-up"><p className="text-sm font-black uppercase tracking-[.22em] text-amber-500">Metro-Atlanta salvage & used foreign parts</p><h1 className="mt-4 max-w-3xl text-4xl font-black leading-[.98] md:text-6xl">Find the right part. Talk to the yard.</h1><p className="mt-5 max-w-2xl text-lg leading-7 text-gray-300">Search real Motherland Auto Parts inventory by vehicle or keyword, decode a VIN, then request the part directly from the yard.</p><div className="mt-7 flex flex-wrap gap-3"><a href="tel:+16785803666" className="focus-ring flex min-h-12 items-center gap-2 bg-[#d97706] px-5 font-black transition-transform hover:-translate-y-0.5"><Phone size={18}/>Call Yard</a><Link href="/inventory" className="focus-ring flex min-h-12 items-center gap-2 border border-white/25 px-5 font-black transition-transform hover:-translate-y-0.5"><Wrench size={18}/>Find a Part <ArrowRight size={17}/></Link></div></div><div className="border border-white/15 bg-white/5 p-5 motion-fade-up motion-delay-1"><div className="flex gap-3"><MapPin className="text-amber-500"/><div><p className="font-black">Lithonia Yard</p><p className="mt-1 text-sm text-gray-300">2182 Coffee Road, Suite G<br/>Lithonia, GA 30058</p></div></div><div className="mt-5 border-t border-white/10 pt-5 text-sm"><span className="font-bold text-white">Need something specific?</span><p className="mt-1 text-gray-400">Send a request and the yard can confirm availability and price.</p></div></div></div><div className="mx-auto max-w-7xl px-4 pb-8"><VehicleLookup/></div></section>
    <VinDecoder/>
    <section className="mx-auto max-w-7xl px-4 py-12 md:py-16"><div className="flex flex-col justify-between gap-4 border-b border-gray-300 pb-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-700">Yard arrivals</p><h2 className="mt-1 text-3xl font-black">Recent inventory</h2></div><Link href="/inventory" className="font-black hover:text-amber-700">View all inventory →</Link></div>{inventoryError?<div className="mt-6 border border-red-200 bg-red-50 p-6"><p className="font-black text-red-900">Inventory is temporarily unavailable.</p><p className="mt-1 text-sm text-red-800">Please call the yard or try the inventory page again.</p><a href="tel:+16785803666" className="mt-4 inline-flex min-h-11 items-center bg-[#111827] px-4 text-sm font-black text-white">Call Yard</a></div>:parts.length?<div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{parts.map(p=><PartCard key={p.id} part={p}/>)}</div>:<EmptyInventory home/>}</section>
    <section className="border-y border-gray-200 bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-12 md:grid-cols-3"><Feature icon={<ShieldCheck/>} title="Real yard inventory" text="Browse parts returned directly from the backend inventory catalogue."/><Feature icon={<Truck/>} title="Vehicle-focused search" text="Narrow by year, make, model and category without guessing at unsupported filters."/><Feature icon={<Phone/>} title="Talk to the yard" text="Request a quote, call, or start a WhatsApp conversation with the part details."/></div></section>
  </main>
}
function EmptyInventory({home=false}:{home?:boolean}){return <div className="mt-6 border border-gray-200 bg-white p-7 sm:p-10 motion-fade-up"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-700">{home?'Recent inventory':'Inventory search'}</p><h3 className="mt-2 text-xl font-black">No parts currently match your search.</h3><p className="mt-2 text-sm leading-6 text-gray-600">Our yard inventory changes frequently. Call the yard for assistance finding a specific part.</p><div className="mt-5 flex flex-col justify-center gap-2 sm:flex-row"><a href="tel:+16785803666" className="inline-flex min-h-11 items-center justify-center bg-[#d97706] px-5 text-sm font-black text-white">Call Yard</a><Link href="/inventory" className="inline-flex min-h-11 items-center justify-center border border-gray-300 px-5 text-sm font-black">Search Inventory</Link></div></div></div>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="border border-gray-200 p-5 transition-transform hover:-translate-y-0.5 motion-fade-up"><div className="text-amber-700">{icon}</div><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-600">{text}</p></div>}
