import Link from 'next/link'; import {MapPin,MessageCircle,Tag} from 'lucide-react'; import type {Part} from '@/types/api'; import {resolveApiUrl} from '@/lib/api/client';
export function PartCard({part,onRequest}:{part:Part;onRequest?:()=>void}){const image=part.images?.find(x=>x.isPrimary)||part.images?.[0];const vehicle=part.vehicles?.[0];const vehicleLabel=vehicle?`${vehicle.yearStart}${vehicle.yearEnd?`–${vehicle.yearEnd}`:''} ${vehicle.make} ${vehicle.model}`:'';const wa=`https://wa.me/16785803666?text=${encodeURIComponent(`Hello Motherland Auto Parts, I am interested in this part:

Part: ${part.title}
SKU: ${part.sku}${vehicle?`
Vehicle: ${vehicleLabel}`:''}

Please confirm availability and price.

Thank you.`)}`;return <article className="motion-card flex h-full flex-col border border-[#e5e7eb] bg-white"><Link href={`/inventory/${part.id}`} className="group block aspect-[4/3] overflow-hidden bg-gray-200">{image?<img src={resolveApiUrl(image.url)} alt={image.altText||part.title} loading="lazy" className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]"/>:<div className="grid h-full place-items-center text-sm font-bold text-gray-500">NO IMAGE</div>}</Link><div className="flex flex-1 flex-col p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-gray-500">{part.category?.name||'Part'}</p><Link href={`/inventory/${part.id}`} className="mt-1 block text-lg font-black hover:text-amber-700">{part.title}</Link></div><div className="flex shrink-0 flex-col items-end gap-1"><span className="border border-gray-200 px-2 py-1 text-[11px] font-black">{part.conditionGrade.replace('_',' ')}</span><span className={`text-[10px] font-black uppercase ${part.inStock?'text-green-700':'text-gray-500'}`}>{part.inStock?'In stock':'Call for availability'}</span></div></div><div className="mt-3 space-y-1 text-sm text-gray-600"><p className="flex items-center gap-2"><Tag size={14}/>SKU {part.sku}</p>{vehicle&&<p>{vehicleLabel}</p>}{part.yardLocation&&<p className="flex items-center gap-2"><MapPin size={14}/>{part.yardLocation}</p>}</div><div className="mt-auto pt-4"><div className="mb-3 font-black">{part.isQuoteOnly||part.price===null?'Request a quote':`$${Number(part.price).toLocaleString()}`}</div><div className="grid grid-cols-2 gap-2"><Link href={`/inventory/${part.id}`} className="focus-ring flex min-h-11 items-center justify-center border border-gray-300 px-3 text-sm font-black">View Details</Link><a href={wa} target="_blank" rel="noreferrer" className="focus-ring flex min-h-11 items-center justify-center gap-1 bg-[#d97706] px-3 text-sm font-black text-white"><MessageCircle size={15}/>Request</a></div>{onRequest&&<button onClick={onRequest} className="mt-2 min-h-11 w-full border border-gray-200 text-xs font-bold">Add to Request</button>}</div></div></article>}
